@echo off
REM ===========================================================================================
REM build.bat - Complete build pipeline for rift
REM ===========================================================================================
REM This script:
REM   1. clang-format - in-place formatting of src/*.cpp / src/*.hpp / src/*.h / src/*.c
REM   2. cmake        - CMake configure via `cmake --preset default` (vcpkg manifest install)
REM   3. clang-tidy   - static analysis using a Ninja sidecar (build-cdb/) for a real
REM                     compile_commands.json. Blocking - the pipeline stops on diagnostics.
REM   4. build        - release and debug build of the configuration via cmake --build
REM   5. doxygen      - HTML documentation
REM ===========================================================================================

setlocal enabledelayedexpansion

REM Get the directory where this script is located
set "SCRIPT_DIR=%~dp0"
cd /d "%SCRIPT_DIR%"

echo ============================================================================
echo                        RIFT BUILD PIPELINE
echo ============================================================================
echo.

REM ============================================================================
REM STEP 1: Run clang-format
REM ============================================================================
echo [1/5] Running clang-format...
echo ----------------------------------------------------------------------------

where clang-format >nul 2>&1
if errorlevel 1 (
    echo SKIP: clang-format not found in PATH
) else (
    for %%f in (src\*.cpp src\*.hpp src\*.h src\*.c) do (
        if exist "%%f" clang-format -i "%%f"
    )
    echo Formatting complete.
)
echo.

REM ============================================================================
REM STEP 2: CMake Configuration
REM ============================================================================
echo [2/5] Configuring with CMake...
echo ----------------------------------------------------------------------------
cmake --preset default
if %ERRORLEVEL% neq 0 (
    echo ERROR: CMake configuration failed
    exit /b %ERRORLEVEL%
)
echo.

REM ============================================================================
REM STEP 3: Run clang-tidy
REM ============================================================================
echo [3/5] Running clang-tidy...
echo ----------------------------------------------------------------------------

where clang-tidy >nul 2>&1
if errorlevel 1 (
    echo SKIP: clang-tidy not found in PATH
) else (
    if not exist "build-cdb\compile_commands.json" (
        echo   Generating compile_commands.json via Ninja sidecar...
        cmake --preset compile-db >nul
        if errorlevel 1 (
            echo ERROR: compile-db configure failed
            exit /b 1
        )
    )

    for %%f in (src\*.cpp tests\*.cpp) do (
        if exist "%%f" (
            echo   tidy: %%f
            clang-tidy --quiet --header-filter="[/\\]%%~nf\.hpp$" -p build-cdb "%%f"
            if errorlevel 1 (
                echo ERROR: clang-tidy reported issues in %%f
                exit /b 1
            )
        )
    )
    echo clang-tidy complete.
)
echo.

REM ============================================================================
REM STEP 4: Build Debug and Release
REM ============================================================================
echo [4/5] Building Debug and Release...
echo ----------------------------------------------------------------------------

echo Building Debug configuration...
cmake --build build --config Debug --target rift
if %errorlevel% neq 0 (
    echo ERROR: Debug build failed!
    exit /b %errorlevel%
)

echo.
echo Building Release configuration...
cmake --build build --config Release --target rift
if %errorlevel% neq 0 (
    echo ERROR: Release build failed!
    exit /b %errorlevel%
)
echo.

REM ============================================================================
REM STEP 5: Generate Doxygen documentation
REM ============================================================================
echo [5/5] Generating Doxygen documentation...
echo ----------------------------------------------------------------------------

REM Check if doxygen is available
where doxygen >nul 2>&1
if %ERRORLEVEL% NEQ 0 (
    echo WARNING: Doxygen not found!
    echo Skipping documentation generation.
    echo To generate docs, install Doxygen: https://www.doxygen.nl/download.html
    goto :skip_doxygen
)

REM Check if Doxyfile exists (generated by CMake from Doxyfile.in)
if not exist "build\Doxyfile" (
    echo WARNING: Doxyfile not found!
    echo Skipping documentation generation.
    goto :skip_doxygen
)

doxygen build\Doxyfile
if %ERRORLEVEL% NEQ 0 (
    echo WARNING: Doxygen generation had issues, but continuing...
) else (
    echo Documentation generated successfully!
)
:skip_doxygen
echo.

REM ============================================================================
REM SUMMARY
REM ============================================================================
echo ============================================================================
echo                        BUILD PIPELINE COMPLETE
echo ============================================================================
echo.
echo Build Output:
echo   Debug:   build\Debug\rift.exe
echo   Release: build\Release\rift.exe

REM Detect linkage type from vcpkg triplet in CMake cache.
set "LINK_TYPE=Dynamic (/MD, x64-windows)"
for /f "tokens=2 delims==" %%t in ('findstr /C:"VCPKG_TARGET_TRIPLET:STRING=" build\CMakeCache.txt 2^>nul') do (
    echo %%t | findstr /i "static" >nul && set "LINK_TYPE=Static (/MT, %%t)"
    echo %%t | findstr /i "static" >nul || set "LINK_TYPE=Dynamic (/MD, %%t)"
)
echo   Linkage: %LINK_TYPE%
echo.
echo Documentation:
echo   - Html: docs\ (if doxygen available)
echo.
echo ============================================================================

endlocal
exit /b 0
