@echo off
REM ============================================================================
REM build.bat - Complete build pipeline for rift
REM ============================================================================
REM This script:
REM   1. Runs clang-format on source files
REM   2. Builds Debug and Release configurations
REM      (CMake handles shader compilation and asset/shader copying)
REM   3. Generates Doxygen documentation
REM ============================================================================

setlocal enabledelayedexpansion

REM Get the directory where this script is located
set "SCRIPT_DIR=%~dp0"
cd /d "%SCRIPT_DIR%"

echo ============================================================================
echo                        RIFT BUILD PIPELINE
echo ============================================================================
echo.

REM ============================================================================
REM STEP 1: Run clang-format
REM ============================================================================
echo [1/3] Running clang-format...
echo ----------------------------------------------------------------------------

where clang-format >nul 2>&1
if errorlevel 1 (
    echo SKIP: clang-format not found in PATH
) else (
    for %%f in (src\*.cpp src\*.h src\*.hpp src\*.c) do (
        if exist "%%f" clang-format -i "%%f"
    )
    echo Formatting complete.
)
echo.

REM ============================================================================
REM STEP 2: Build Debug and Release
REM ============================================================================
echo [2/3] Building Debug and Release...
echo ----------------------------------------------------------------------------

if not exist build mkdir build
cd build

echo Configuring CMake...
cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
if %errorlevel% neq 0 (
    echo ERROR: CMake configuration failed!
    pause
    exit /b %errorlevel%
)

echo.
echo Building Debug configuration...
cmake --build . --config Debug
if %errorlevel% neq 0 (
    echo ERROR: Debug build failed!
    pause
    exit /b %errorlevel%
)

echo.
echo Building Release configuration...
cmake --build . --config Release
if %errorlevel% neq 0 (
    echo ERROR: Release build failed!
    pause
    exit /b %errorlevel%
)

cd /d "%SCRIPT_DIR%"
echo.

REM ============================================================================
REM STEP 3: Generate Doxygen documentation
REM ============================================================================
echo [3/3] Generating Doxygen documentation...
echo ----------------------------------------------------------------------------

REM Check if doxygen is available
where doxygen >nul 2>&1
if %ERRORLEVEL% NEQ 0 (
    echo WARNING: Doxygen not found!
    echo Skipping documentation generation.
    echo To generate docs, install Doxygen: https://www.doxygen.nl/download.html
    goto :skip_doxygen
)

REM Check if Doxyfile exists (generated by CMake from Doxyfile.in)
if not exist "build\Doxyfile" (
    echo WARNING: Doxyfile not found!
    echo Skipping documentation generation.
    goto :skip_doxygen
)

doxygen build\Doxyfile
if %ERRORLEVEL% NEQ 0 (
    echo WARNING: Doxygen generation had issues, but continuing...
) else (
    echo Documentation generated successfully!
)
:skip_doxygen
echo.

REM ============================================================================
REM SUMMARY
REM ============================================================================
echo ============================================================================
echo                        BUILD PIPELINE COMPLETE
echo ============================================================================
echo.
echo Build Output:
echo   Debug:   build\Debug\rift.exe
echo   Release: build\Release\rift.exe

REM Detect linkage type from vcpkg triplet in CMake cache.
set "LINK_TYPE=Dynamic (/MD, x64-windows)"
for /f "tokens=2 delims==" %%t in ('findstr /C:"VCPKG_TARGET_TRIPLET:STRING=" build\CMakeCache.txt 2^>nul') do (
    echo %%t | findstr /i "static" >nul && set "LINK_TYPE=Static (/MT, %%t)"
    echo %%t | findstr /i "static" >nul || set "LINK_TYPE=Dynamic (/MD, %%t)"
)
echo   Linkage: %LINK_TYPE%
echo.
echo Documentation:
echo   - Html: docs\ (if doxygen available)
echo.
echo ============================================================================

endlocal
exit /b 0
